### ISSUE TITLE
CSS child selector ignored

### ISSUE THREAD

**Issue by tornography** [AmirTugi/tea-school#1]
Hi,

I tried tea-school and it's working so far. But there seems to be an issue with the with some css selectors. An example can be viewed at https://codepen.io/tornography/pen/yRxEdv but for later reference here is the code, that causes the problem.

index.pug
```pug
.grid
    div left
    div right
```

index.scss
```scss
.grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    grid-gap: 1em;
}

.grid > * {
    background-color: red;
    color: black;
    border: 2px solid black;
    padding: 0.5em;
}
```
Behavior: The child selector `.grid > *` is ignored.
Expected: The innerboxes should have a red background and black borders.

I tried the linked example from above to convert it with puppeteer itself withoud problems. An online tool (https://puppeteer-html2pdf.herokuapp.com/), using puppeteer trying to convert the example works as well. So I am quite shure puppeteer is not the issue.

I output the `#{compiledStyle}` in the generated PDF that looks good as well.

Regards,
Manuel
